name: CI

on:
  pull_request:
    branches:
      - dev
      - main

  push:
    branches:
      - dev
      - main

jobs:
  quality:
    runs-on: ubuntu-latest

    env:
        PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.20.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Payload secret
        run: |
          if [ -n "$PAYLOAD_SECRET" ]; then
            echo "PAYLOAD_SECRET is available"
          else
            echo "PAYLOAD_SECRET is NOT available"
            exit 1
          fi

      - name: Build
        run: npm run build
